#!/usr/bin/with-contenv bash

# make folders
mkdir -p /var/spool/cron/crontabs

# delete existing pid if found
[[ -e /var/run/crond.pid ]] rm -rf /var/run/crond.pid

# Setup cron to cycle lirc every hour
echo "0	*	*	*	*	pkill lirc" > /var/spool/cron/crontabs/root
